module.exports = {
	beforeCreateOrderFileRequest: require('./create-order-file-request').before,
	beforeCreateOrderRequest: require('./create-order-request').before,
	beforeGetOrdersRequest: require('./get-orders-request').before,
	beforeCreateOrderCommentRequest: require('./create-order-comment-request').before,
	beforeDeleteOrderRequest: require('./delete-order-request').before,
	beforeCompleteOrderRequest: require('./complete-order-request').before,
	beforeTrackOrderRequest: require('./track-order-request').before,
	beforeAcceptOrderRequest: require('./accept-order-request').before,
	beforeResolveOrderRequest: require('./resolve-order-request').before,
	beforeGetOrderCommentsRequest: require('./get-order-comments-request').before,
	beforeDeleteOrderFileRequest: require('./delete-order-file-request').before,
	beforeReadOrderRequest: require('./read-order-request').before,
	afterCompleteOrderRequest: require('./complete-order-request').after,
	afterTrackOrderRequest: require('./track-order-request').after,
	afterCreateOrderRequest: require('./create-order-request').after,
	afterCreateOrderCommentRequest: require('./create-order-comment-request').after,
	afterDeleteOrderRequest: require('./delete-order-request').after,
	afterCreateOrderFileRequest: require('./create-order-file-request').after,
	afterAcceptOrderRequest: require('./accept-order-request').after,
	afterResolveOrderRequest: require('./resolve-order-request').after,
};
