// Notify handler
import { notifyHandlerActions } from '../../../lib/notify-handler';
export const { CATCH_NOTIFY_HANDLER } = notifyHandlerActions;

// Application
export const START_INITIALIZE_CONSUMER_APPLICATION = 'START_INITIALIZE_CONSUMER_APPLICATION';
export const INITIALIZE_CONSUMER_APPLICATION_SUCCESS = 'INITIALIZE_CONSUMER_APPLICATION_SUCCESS';
export const INITIALIZE_CONSUMER_APPLICATION_FAILED = 'INITIALIZE_CONSUMER_APPLICATION_FAILED';

// Auth
export const START_CHECK_AUTH = 'START_CHECK_AUTH';
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS';
export const CHECK_AUTH_FAILED = 'CHECK_AUTH_FAILED';

export const UPDATE_ME_CHANNELS = 'UPDATE_ME_CHANNELS';

export const START_LOGIN = 'START_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const START_LOGOUT = 'START_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

// Provider application
export const START_INITIALIZE_PROVIDER_APPLICATION = 'START_INITIALIZE_PROVIDER_APPLICATION';
export const INITIALIZE_PROVIDER_APPLICATION_SUCCESS = 'INITIALIZE_PROVIDER_APPLICATION_SUCCESS';
export const INITIALIZE_PROVIDER_APPLICATION_FAILED = 'INITIALIZE_PROVIDER_APPLICATION_FAILED';

// Channel
export const SET_SELECTED_CHANNEL = 'SET_SELECTED_CHANNEL';

// Orders
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';
export const RESET_ORDERS = 'RESET_ORDERS';

export const START_FETCH_PROCESSING_ORDERS = 'START_FETCH_PROCESSING_ORDERS';
export const FETCH_PROCESSING_ORDERS_SUCCESS = 'FETCH_PROCESSING_ORDERS_SUCCESS';
export const FETCH_PROCESSING_ORDERS_FAILED = 'FETCH_PROCESSING_ORDERS_FAILED';

export const START_FETCH_TRACKED_ORDERS = 'START_FETCH_TRACKED_ORDERS';
export const FETCH_TRACKED_ORDERS_SUCCESS = 'FETCH_TRACKED_ORDERS_SUCCESS';
export const FETCH_TRACKED_ORDERS_FAILED = 'FETCH_TRACKED_ORDERS_FAILED';

export const START_FETCH_CLOSED_ORDERS = 'START_FETCH_CLOSED_ORDERS';
export const FETCH_CLOSED_ORDERS_SUCCESS = 'FETCH_CLOSED_ORDERS_SUCCESS';
export const FETCH_CLOSED_ORDERS_FAILED = 'FETCH_CLOSED_ORDERS_FAILED';

export const SET_PROCESSING_SEARCH_QUERIES = 'SET_PROCESSING_SEARCH_QUERIES';
export const SET_TRACKED_SEARCH_QUERIES = 'SET_TRACKED_SEARCH_QUERIES';
export const SET_CLOSED_SEARCH_QUERIES = 'SET_CLOSED_SEARCH_QUERIES';
export const SET_PROCESSING_NUM_OF_ITEMS = 'SET_PROCESSING_NUM_OF_ITEMS';
export const SET_TRACKED_NUM_OF_ITEMS = 'SET_TRACKED_NUM_OF_ITEMS';

export const START_FETCH_PROCESSING_ORDERS_NUMBER_OF_ITEMS = 'START_FETCH_PROCESSING_ORDERS_NUMBER_OF_ITEMS';
export const START_FETCH_TRACKED_ORDERS_NUMBER_OF_ITEMS = 'START_FETCH_TRACKED_ORDERS_NUMBER_OF_ITEMS';

// Order
export const START_CREATE_ORDER = 'START_CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED';

export const START_FETCH_ORDER = 'START_FETCH_ORDER';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILED = 'FETCH_ORDER_FAILED';

export const SET_SELECTED_ORDER_ID = 'SET_SELECTED_ORDER_ID';
export const RESET_SELECTED_ORDER_ID = 'RESET_SELECTED_ORDER_ID';

export const START_FETCH_NEXT_PROCESSING_ORDERS = 'START_FETCH_NEXT_PROCESSING_ORDERS';
export const FETCH_NEXT_PROCESSING_ORDERS_SUCCESS = 'FETCH_NEXT_PROCESSING_ORDERS_SUCCESS';
export const FETCH_NEXT_PROCESSING_ORDERS_FAILED = 'FETCH_NEXT_PROCESSING_ORDERS_FAILED';

export const START_DELETE_ORDER = 'START_DELETE_ORDER';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILED = 'DELETE_ORDER_FAILED';

export const START_COMPLETE_ORDER = 'START_COMPLETE_ORDER';
export const COMPLETE_ORDER_SUCCESS = 'COMPLETE_ORDER_SUCCESS';
export const COMPLETE_ORDER_FAILED = 'COMPLETE_ORDER_FAILED';

export const START_TRACK_ORDER = 'START_TRACK_ORDER';
export const TRACK_ORDER_SUCCESS = 'TRACK_ORDER_SUCCESS';
export const TRACK_ORDER_FAILED = 'TRACK_ORDER_FAILED';

export const START_ACCEPT_ORDER = 'START_ACCEPT_ORDER';
export const ACCEPT_ORDER_SUCCESS = 'ACCEPT_ORDER_SUCCESS';
export const ACCEPT_ORDER_FAILED = 'ACCEPT_ORDER_FAILED';

export const START_RESOLVE_ORDER = 'START_RESOLVE_ORDER';
export const RESOLVE_ORDER_SUCCESS = 'RESOLVE_ORDER_SUCCESS';
export const RESOLVE_ORDER_FAILED = 'RESOLVE_ORDER_FAILED';

export const START_INVITE_ORDER = 'START_INVITE_ORDER';
export const INVITE_ORDER_SUCCESS = 'INVITE_ORDER_SUCCESS';
export const INVITE_ORDER_FAILED = 'INVITE_ORDER_FAILED';

export const START_ACCEPT_INVITATION_ORDER = 'START_ACCEPT_INVITATION_ORDER';
export const ACCEPT_INVITATION_SUCCESS_ORDER = 'ACCEPT_INVITATION_SUCCESS_ORDER';
export const ACCEPT_INVITATION_FAILED_ORDER = 'ACCEPT_INVITATION_FAILED_ORDER';

export const APPEND_ORDER_FILE = 'APPEND_ORDER_FILE';
export const UPDATE_HAS_NEW_ACTIVITY = 'UPDATE_HAS_NEW_ACTIVITY';
export const APPEND_ORDER_COMMENT = 'APPEND_ORDER_COMMENT';

export const APPEND_INVITATION = 'APPEND_INVITATION';
export const REMOVE_INVITATION = 'REMOVE_INVITATION';
export const UPDATE_ORDER_FROM_INVITATION_UPDATED = 'UPDATE_ORDER_FROM_INVITATION_UPDATED';
export const ADD_ORDER_FROM_INVITATION_UPDATED = 'ADD_ORDER_FROM_INVITATION_UPDATED';
export const REMOVE_ORDER_FROM_INVITATION_UPDATED = 'REMOVE_ORDER_FROM_INVITATION_UPDATED';

export const ADD_ACCEPTED_INVITATION_ORDER = 'ADD_ACCEPTED_INVITATION_ORDER';
export const REMOVE_ACCEPTED_INVITATION_ORDER = 'REMOVE_ACCEPTED_INVITATION_ORDER';

export const START_UPDATE_ORDER_NUMBER = 'START_UPDATE_ORDER_NUMBER';
export const UPDATE_ORDER_NUMBER_SUCCESS = 'UPDATE_ORDER_NUMBER_SUCCESS';
export const UPDATE_ORDER_NUMBER_FAILED = 'UPDATE_ORDER_NUMBER_FAILED';

// Tag
export const START_FETCH_TAGS = 'START_FETCH_TAGS';
export const FETCH_TAGS_SUCCESS = 'FETCH_TAGS_SUCCESS';
export const FETCH_TAGS_FAILED = 'FETCH_TAGS_FAILED';

export const UPDATE_TAGS = 'UPDATE_TAGS';

// Comment
export const START_FETCH_COMMENTS = 'START_FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAILED = 'FETCH_COMMENTS_FAILED';

export const START_CREATE_COMMENT = 'START_CREATE_COMMENT';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';

export const RESET_COMMENTS = 'RESET_COMMENTS';

// File
export const START_UPLOAD_FILE = 'START_UPLOAD_FILE';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

// Consumer Orders
export const SET_CONSUMER_SELECTED_TAB = 'SET_CONSUMER_SELECTED_TAB';
export const SET_CONSUMER_PROCESSING_SEARCH_QUERIES = 'SET_CONSUMER_PROCESSING_SEARCH_QUERIES';
export const SET_CONSUMER_TRACKED_SEARCH_QUERIES = 'SET_CONSUMER_TRACKED_SEARCH_QUERIES';
export const SET_CONSUMER_CLOSED_SEARCH_QUERIES = 'SET_CONSUMER_CLOSED_SEARCH_QUERIES';

export const START_FETCH_CONSUMER_PROCESSING_ORDERS = 'START_FETCH_CONSUMER_PROCESSING_ORDERS';
export const FETCH_CONSUMER_PROCESSING_ORDERS_SUCCESS = 'FETCH_CONSUMER_PROCESSING_ORDERS_SUCCESS';
export const FETCH_CONSUMER_PROCESSING_ORDERS_FAILED = 'FETCH_CONSUMER_PROCESSING_ORDERS_FAILED';

export const START_FETCH_CONSUMER_TRACKED_ORDERS = 'START_FETCH_CONSUMER_TRACKED_ORDERS';
export const FETCH_CONSUMER_TRACKED_ORDERS_SUCCESS = 'FETCH_CONSUMER_TRACKED_ORDERS_SUCCESS';
export const FETCH_CONSUMER_TRACKED_ORDERS_FAILED = 'FETCH_CONSUMER_TRACKED_ORDERS_FAILED';

export const START_FETCH_CONSUMER_CLOSED_ORDERS = 'START_FETCH_CONSUMER_CLOSED_ORDERS';
export const FETCH_CONSUMER_CLOSED_ORDERS_SUCCESS = 'FETCH_CONSUMER_CLOSED_ORDERS_SUCCESS';
export const FETCH_CONSUMER_CLOSED_ORDERS_FAILED = 'FETCH_CONSUMER_CLOSED_ORDERS_FAILED';

export const START_FETCH_CONSUMER_NEXT_PROCESSING_ORDERS = 'START_FETCH_CONSUMER_NEXT_PROCESSING_ORDERS';
export const FETCH_CONSUMER_NEXT_PROCESSING_ORDERS_SUCCESS = 'FETCH_CONSUMER_NEXT_PROCESSING_ORDERS_SUCCESS';
export const FETCH_CONSUMER_NEXT_PROCESSING_ORDERS_FAILED = 'FETCH_CONSUMER_NEXT_PROCESSING_ORDERS_FAILED';

export const START_UPDATE_HAD_READ_ORDER = 'START_UPDATE_HAD_READ_ORDER';
export const UPDATE_HAD_READ_ORDER_SUCCESS = 'UPDATE_HAD_READ_ORDER_SUCCESS';
export const UPDATE_HAD_READ_ORDER_FAILED = 'UPDATE_HAD_READ_ORDER_FAILED';

export const SET_CONSUMER_PROCESSING_NUM_OF_ITEMS = 'SET_CONSUMER_PROCESSING_NUM_OF_ITEMS';
export const SET_CONSUMER_TRACKED_NUM_OF_ITEMS = 'SET_CONSUMER_TRACKED_NUM_OF_ITEMS';

export const START_FETCH_CONSUMER_PROCESSING_ORDERS_NUMBER_OF_ITEMS = 'START_FETCH_CONSUMER_PROCESSING_ORDERS_NUMBER_OF_ITEMS';
export const START_FETCH_CONSUMER_TRACKED_ORDERS_NUMBER_OF_ITEMS = 'START_FETCH_CONSUMER_TRACKED_ORDERS_NUMBER_OF_ITEMS';

// Created Orders
export const START_FETCH_CREATED_ORDERS = 'START_FETCH_CREATED_ORDERS';
export const FETCH_CREATED_ORDERS_SUCCESS = 'FETCH_CREATED_ORDERS_SUCCESS';
export const FETCH_CREATED_ORDERS_FAILED = 'FETCH_CREATED_ORDERS_FAILED';

export const START_FETCH_NEXT_CREATED_ORDERS = 'START_FETCH_NEXT_CREATED_ORDERS';
export const FETCH_NEXT_CREATED_ORDERS_SUCCESS = 'FETCH_NEXT_CREATED_ORDERS_SUCCESS';
export const FETCH_NEXT_CREATED_ORDERS_FAILED = 'FETCH_NEXT_CREATED_ORDERS_FAILED';

// Favorites channels
export const START_UPDATE_CHANNEL_SETTINGS = 'START_UPDATE_CHANNEL_SETTINGS';
export const UPDATE_CHANNEL_SETTINGS_SUCCESS = 'UPDATE_CHANNEL_SETTINGS_SUCCESS';
export const UPDATE_CHANNEL_SETTINGS_FAILED = 'UPDATE_CHANNEL_SETTINGS_FAILED';
export const SET_CREATED_ORDERS_NUM_OF_ITEMS = 'SET_CREATED_ORDERS_NUM_OF_ITEMS';

// Online Users
export const START_FETCH_ONLINE_USERS = 'START_FETCH_ONLINE_USERS';
export const FETCH_ONLINE_USERS_SUCCESS = 'FETCH_ONLINE_USERS_SUCCESS';
export const FETCH_ONLINE_USERS_FAILED = 'FETCH_ONLINE_USERS_FAILED';

// Bind socket
export const ON_ORDER_CREATED = 'ON_ORDER_CREATED';
export const ON_ORDER_UPDATED = 'ON_ORDER_UPDATED';
export const SOCKET_INSERT_ONE_OF_ORDERS = 'SOCKET_INSERT_ONE_OF_ORDERS';
export const SOCKET_APPEND_CREATED_ORDER = 'SOCKET_APPEND_CREATED_ORDER';
